### ISSUE TITLE
meeting review

### ISSUE THREAD

**Issue by omar-labana** [IbrohimRasulov/Microverse-Website-clone#2]
clean imitation and coding.

**Comment by rotimiazeez** [comment]
distinct coding I'll implore the use of add rather than added in the commits, added can be used after the review when changing or adding some things, but I don't think it's ideal before the review.

**Comment by bettercallsully** [comment]
I have no issues with Ibrohim's code here, also enjoyed the concept and the speed he was able to code the page and complete it within a weekend.

**Comment by rotimiazeez** [comment]
Thumb up, mate.
